In [7]:
import numpy as np

a = np.eye(3) ### 행렬 대각선만 1을 채운다.
b = np.eye(3, 4)
c = np.linspace(10, 20, 5) ### 10 ~ 20을 5개로 나눠라.
print(a)
print(b)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[10.  12.5 15.  17.5 20. ]


In [10]:
a = np.arange(6)
print(a)

b = a.reshape(3, 2)
print(b)

print(np.transpose(b)) ### 행과 열을 서로 바꾼다.
                       ### 행이 열이 되고
                       ### 열이 행이 된다.

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]
[[0 2 4]
 [1 3 5]]


**np**

- 행렬 덧셈, 곱셈 가능하다.
- 행렬 요소 올림, 내림, 반올림 전부 가능하다.
- 